AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  An Amazon S3 trigger that retrieves metadata for the object that has been
  updated.
Resources:
  indexphotoscopy:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-copy
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./index-photos-copy
      Description: >-
        An Amazon S3 trigger that retrieves metadata for the object that has
        been updated.
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::616117645092:role/service-role/index-photos-role'
      Environment:
        Variables:
          REGION: us-east-1
  searchphotoscopy:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: search-photos-copy
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos-copy
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::616117645092:role/service-role/search-photos-role-3ec6y0uc'
      Environment:
        Variables:
          REGION: us-east-1
